import AppLayout from "../components/layout/AppLayout";
import PageWrapper from "../components/layout/PageWrapper";

import BehaviorChart from "../components/dashboard/BehaviorChart";
import ActivityFeed from "../components/dashboard/ActivityFeed";
import ConfidenceGauge from "../components/dashboard/ConfidenceGauge";
import StatsOverview from "../components/dashboard/StatsOverview";
import AnimatedCard from "../components/layout/AnimatedCard";
import RadarMetrics from "../components/dashboard/RadarMetrics";
import AIAnalysis from "../components/dashboard/AIAnalysis";

import { behaviorData } from "../data/mockBehaviorData";

export default function Dashboard() {
  return (
    <AppLayout>
      <PageWrapper>
        <div className="space-y-6">
          {/* HEADER */}

          <div>
            <div className="flex items-center gap-3">
              <div className="h-2 w-2 rounded-full bg-green-500 animate-pulse" />

              <p className="text-xs uppercase tracking-[0.4em] text-yellow-500">
                Live Analysis Running
              </p>
            </div>

            <h1 className="luxury-title mt-3 text-4xl font-semibold">
              System Overview
            </h1>

            <p className="mt-3 text-zinc-500">
              Live behavioral and intelligence insights generated by Chronis.
            </p>
          </div>

          {/* KPI SECTION */}

          <div className="grid gap-5 lg:grid-cols-4">
            <AnimatedCard className="gold-card rounded-2xl p-5">
              <p className="text-sm text-zinc-500">
                Behavioral Score
              </p>

              <h2 className="mt-3 text-5xl font-bold text-yellow-400">
                94              </h2>

              <p className="mt-2 text-sm text-emerald-400">
                +12.4%
              </p>
            </AnimatedCard>

            <AnimatedCard className="gold-card rounded-2xl p-5">
              <p className="text-sm text-zinc-500">
                Confidence
              </p>

              <h2 className="mt-3 text-4xl font-bold">
                88%
              </h2>

              <div className="mt-4 h-2 rounded-full bg-zinc-800">
                <div className="h-2 w-[88%] rounded-full bg-yellow-500" />
              </div>
            </AnimatedCard>

            <AnimatedCard className="gold-card rounded-2xl p-5">
              <p className="text-sm text-zinc-500">
                System Status
              </p>

              <h2 className="mt-3 text-3xl font-semibold">
                Nominal
              </h2>

              <p className="mt-2 text-yellow-400">
                Stable
              </p>
            </AnimatedCard>

            <AnimatedCard className="gold-card rounded-2xl p-5">
              <p className="text-sm text-zinc-500">
                Active Signals
              </p>

              <h2 className="mt-3 text-4xl font-bold">
                1024              </h2>

              <p className="mt-2 text-zinc-500">
                Last 24 Hours
              </p>
            </AnimatedCard>
          </div>

          {/* STATS */}

          <StatsOverview />

          {/* CHART + SUMMARY */}

          <div className="grid gap-5 lg:grid-cols-3">
            <div className="lg:col-span-2">
              <div className="gold-card rounded-2xl p-5">
                <BehaviorChart data={behaviorData} />
              </div>
            </div>

            <div>
              <div className="gold-card rounded-2xl p-5">
                <h2 className="text-lg font-semibold text-yellow-400">
                  Intelligence Summary
                </h2>

                <p className="mt-4 leading-7 text-zinc-400">
                  Productivity and sleep consistency have improved
                  steadily over the last quarter. Confidence in
                  long-term behavioral stability continues to rise.
                </p>

                <p className="mt-4 leading-7 text-zinc-400">
                  Chronis detected a positive trend in focus,
                  habit consistency and behavioral stability.
                </p>
              </div>
            </div>
          </div>

          {/* SECOND ROW */}

          <div className="grid gap-5 lg:grid-cols-2">
            <ActivityFeed />

            <ConfidenceGauge />

            <AIAnalysis />
          </div>
<RadarMetrics />

          {/* RECENT LOGS */}

          <div className="gold-card rounded-2xl p-5">
            <div className="mb-5 flex items-center justify-between">
              <h2 className="text-xl font-semibold">
                Recent Intelligence Logs
              </h2>

              <button className="text-sm text-yellow-400">
                View All
              </button>
            </div>

            <div className="space-y-3">
              <div className="rounded-xl border border-white/5 bg-black/30 p-4">
                Behavioral anomaly detected and reviewed.
              </div>

              <div className="rounded-xl border border-white/5 bg-black/30 p-4">
                Sleep consistency improved by 18%.
              </div>

              <div className="rounded-xl border border-white/5 bg-black/30 p-4">
                Focus recalibration completed successfully.
              </div>

              <div className="rounded-xl border border-white/5 bg-black/30 p-4">
                Confidence score updated after signal ingestion.
              </div>
            </div>
          </div>
        </div>
      </PageWrapper>
    </AppLayout>
  );
}


